force-app/main/default/objects/ScratchOrgAlertEmail__c/ScratchOrgAlertEmail__c.object-meta.xml
<CustomObject>
    <description>Represents the email sent out by the Scratch Org Alert app.</description>
    <label>Scratch Org Alert Email</label>
    <nameField>
        <label>Scratch Org Alert Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scratch Org Alert Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ScratchOrgAlertEmail__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User for whom a Scratch Org Alert email has been generated</description>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scratch_Org_Alert_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/ScratchOrgAlertEmailItem__c.object-meta.xml
<CustomObject>
    <description>Represent the information for each expiring scratch org in an email.</description>
    <label>Scratch Org Alert Email Item</label>
    <nameField>
        <label>Scratch_Org_Alert_Email_Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scratch Org Alert Email Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/ScratchOrgAlertEmail__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertEmail__c</fullName>
    <description>The alert email that this email item is a part of.</description>
    <label>Scratch Org Alert Email</label>
    <referenceTo>ScratchOrgAlertEmail__c</referenceTo>
    <relationshipLabel>Scratch Org Alert Email Items</relationshipLabel>
    <relationshipName>Scratch_Org_Alert_Email_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScratchOrgAlertEmailer.cls
public with sharing class ScratchOrgAlertEmailer {
    private static Boolean inspectResults(Messaging.SendEmailResult[] results) {
        Boolean sendResult = true;
        for (Messaging.SendEmailResult res : results) {
            if (res.isSuccess()) {
                System.debug('Email sent successfully');
            } else {
                sendResult = false;
                System.debug('The following errors occurred: ' + res.getErrors());
            }
        }
        return sendResult;
    }

    public static void purgeEmailObjects() {
        if (ScratchOrgAlertEmail__c.SObjectType.getDescribe().isDeletable())
            delete [SELECT Id FROM ScratchOrgAlertEmail__c];
        else
            System.debug(LoggingLevel.ERROR, 'You don\'t have permission to delete ScratchOrgAlertEmail__c; that\'s a problem.');

        // Just in case there are email items that weren't deleted along with their parents
        if (ScratchOrgAlertEmailItem__c.SObjectType.getDescribe().isDeletable())
            delete [SELECT Id FROM ScratchOrgAlertEmailItem__c];
        else
            System.debug(LoggingLevel.ERROR, 'You don\'t have permission to delete ScratchOrgAlertEmailItem__c; that\'s a problem.');
    }

    public static Boolean sendEmails(Map<Id, String> recipients, List<ScratchOrgAlertEmail__c> alertEmails) {
        if (ScratchOrgAlert.isObjectAccessible(Schema.SObjectType.EmailTemplate, ScratchOrgAlert.EmailTemplateFields)) {
            List<EmailTemplate> templates = [SELECT Id, Body FROM EmailTemplate WHERE DeveloperName = 'ScratchOrgAlert'];

            if (templates.size() == 0) {
                System.debug(LoggingLevel.ERROR, 'No templates returned by template query; you may not have permission to access the template.');
            } else if (templates.size() == 1) {
                EmailTemplate template = templates[0];

                List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
                for (ScratchOrgAlertEmail__c email : alertEmails) {
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();

                    message.setToAddresses(new String[] {recipients.get(email.UserId__c)});
                    message.setTargetObjectId(email.UserId__c);
                    message.setTemplateId(template.Id);
                    message.setWhatId(email.Id);
                    message.saveAsActivity = false;

                    messages.add(message);
                }

                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
                purgeEmailObjects();
                return inspectResults(results);
            } else {
                System.debug(LoggingLevel.ERROR, 'Multiple templates returned by template query.');
            }
        }
        return false;
    }
}