force-app/main/default/objects/ScratchOrgAlertEmail__c/ScratchOrgAlertEmail__c.object-meta.xml
<CustomObject>
    <description>Represents the email sent out by the Scratch Org Alert app.</description>
    <label>Scratch Org Alert Email</label>
    <nameField>
        <label>Scratch Org Alert Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scratch Org Alert Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ScratchOrgAlertEmail__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User for whom a Scratch Org Alert email has been generated</description>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scratch_Org_Alert_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/ScratchOrgAlertEmailItem__c.object-meta.xml
<CustomObject>
    <description>Represent the information for each expiring scratch org in an email.</description>
    <label>Scratch Org Alert Email Item</label>
    <nameField>
        <label>Scratch_Org_Alert_Email_Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scratch Org Alert Email Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/CreatedById__c.field-meta.xml
<CustomField>
    <fullName>CreatedById__c</fullName>
    <label>Created By Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/LastModifiedById__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedById__c</fullName>
    <label>Last Modified By Ids</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/LastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate__c</fullName>
    <label>System Modstamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <label>Org Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <label>Owner Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/ScratchOrg__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrg__c</fullName>
    <label>Scratch Org</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/ScratchOrgAlertEmail__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertEmail__c</fullName>
    <description>The alert email that this email item is a part of.</description>
    <label>Scratch Org Alert Email</label>
    <referenceTo>ScratchOrgAlertEmail__c</referenceTo>
    <relationshipLabel>Scratch Org Alert Email Items</relationshipLabel>
    <relationshipName>Scratch_Org_Alert_Email_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/ScratchOrgInfoId__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgInfoId__c</fullName>
    <label>Scratch Org Info Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/SignupEmail__c.field-meta.xml
<CustomField>
    <fullName>SignupEmail__c</fullName>
    <label>Signup Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/SignupInstance__c.field-meta.xml
<CustomField>
    <fullName>SignupInstance__c</fullName>
    <label>Signup Instance</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/SignupTrialDays__c.field-meta.xml
<CustomField>
    <fullName>SignupTrialDays__c</fullName>
    <label>Signup Trial Days</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/SignupUsername__c.field-meta.xml
<CustomField>
    <fullName>SignupUsername__c</fullName>
    <label>Signup Username</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScratchOrgAlertEmailItem__c/fields/SystemModstamp__c.field-meta.xml
<CustomField>
    <fullName>SystemModstamp__c</fullName>
    <label>System Modstamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/ScratchOrgAlertEnabled__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows a user to opt into receiving Scratch Org expiration alerts.</description>
    <label>Scratch Org Alert Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/ScratchOrgAlertNotificationDays__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertNotificationDays__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of days before a Scratch Org&#39;s expiration that a user should be alerted for.</description>
    <label>Scratch Org Alert Notification Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/ScratchOrgAlertRecipient__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertRecipient__c</fullName>
    <description>The email address that is notified by the Scratch Org Alert app.</description>
    <label>Scratch Org Alert Recipient</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ScratchOrgAlert.cls
public with sharing class ScratchOrgAlert implements Schedulable {

    public static String[] ActiveScratchOrgQueryFields = new String[] {
        'CreatedById', 'CreatedDate',
        'Description', 'Edition', 'ExpirationDate',
        'Id', 'LastLoginDate', 'LastModifiedById',
        'LastModifiedDate', 'LastViewedDate', 'Name',
        'Namespace', 'OrgName', 'OwnerId',
        'ScratchOrg', 'ScratchOrgInfoId', 'SignupEmail',
        'SignupInstance', 'SignupTrialDays', 'SignupUsername',
        'SystemModstamp'
    };

    public static String[] UserQueryFields = new String[] {
        'Id', 'Email', 'ScratchOrgAlertNotificationDays__c',
        'ScratchOrgAlertRecipient__c', 'ScratchOrgAlertEnabled__c'
    };
    
    public static String[] CronJobFields = new String[] {'Name', 'Id'};

    public static String[] CronTriggerFields = new String[] {'CronJobDetailId'};

    public static String[] EmailQueryFields = new String[] {'UserId__c'};

    public static String[] EmailItemQueryFields = new String[] {
        'CreatedById__c', 'CreatedDate__c',
        'Description__c', 'Edition__c',
        'ExpirationDate__c', 'LastLoginDate__c', 'LastModifiedById__c',
        'LastModifiedDate__c', 'LastViewedDate__c', 'Name__c',
        'Namespace__c', 'OrgName__c', 'OwnerId__c',
        'ScratchOrg__c', 'ScratchOrgAlertEmail__c', 'ScratchOrgInfoId__c', 
        'SignupEmail__c', 'SignupInstance__c', 'SignupTrialDays__c', 
        'SystemModstamp__c', 'SignupUsername__c'
    };

    public static String[] EmailTemplateFields = new String[] {'Id', 'Body', 'DeveloperName'};

    public void execute(SchedulableContext cntx) {
        run();
    }

    // Run for all users with active orgs
    public static void run() {
        Map<Id, List<ActiveScratchOrg>> orgs = queryActiveOrgs();
        emailOrgOwners(orgs);
    }

    // Run for specific set of users (used in trigger)
    public static void run(List<User> u) {
        Map<Id, List<ActiveScratchOrg>> orgs = queryActiveOrgs(u);
        emailOrgOwners(orgs);
    }

    // Find all scratch orgs
    public static Map<Id, List<ActiveScratchOrg>> queryActiveOrgs() {
        if (ScratchOrgAlert.isObjectAccessible(Schema.SObjectType.User, ScratchOrgAlert.UserQueryFields)) {
            return queryActiveOrgs(Database.query('SELECT ' + String.join(ScratchOrgAlert.UserQueryFields, ', ') + ' FROM User WHERE ScratchOrgAlertEnabled__c = true'));
        } else {
            System.debug(LoggingLevel.ERROR, 'You don\'t have access to the user fields required.');
            return new Map<Id, List<ActiveScratchOrg>>();
        }
    }

    // Find all scratch orgs for a specific subset of users
    public static Map<Id, List<ActiveScratchOrg>> queryActiveOrgs(List<User> users) {
        List<Id> userIds = new List<Id>();
        Map<Id, Integer> userNotificationDays = new Map<Id, Integer>();
        Map<Id, List<ActiveScratchOrg>> notifiableOrgs = new Map<Id, List<ActiveScratchOrg>>();

        for (User u : users) {
            if (!u.ScratchOrgAlertEnabled__c) {
                System.debug('Feature disabled. Skipping user.');
                continue;
            }

            if (String.isBlank(u.ScratchOrgAlertRecipient__c)) {
                System.debug('Recipient email not set. Skipping user.');
                continue;
            }

            if (u.ScratchOrgAlertNotificationDays__c == null || u.ScratchOrgAlertNotificationDays__c < 1) {
                System.debug('Alert duration before not set. Skipping user.');
                continue;
            }

            userIds.add(u.Id);
            userNotificationDays.put(u.Id, Integer.valueOf(u.ScratchOrgAlertNotificationDays__c));
        }

        if (ScratchOrgAlert.isObjectAccessible(Schema.SObjectType.ActiveScratchOrg, ScratchOrgAlert.ActiveScratchOrgQueryFields)) {
            List<ActiveScratchOrg> activeOrgs = Database.query('SELECT ' +
                String.join(ScratchOrgAlert.ActiveScratchOrgQueryFields, ', ') +
                ' FROM ActiveScratchOrg WHERE IsDeleted = false AND OwnerId IN :userIds'
            );

            for (ActiveScratchOrg org : activeOrgs) {
                Integer notificationDays = userNotificationDays.get(org.OwnerId);
                if (businessDaysBetween(System.today(), org.expirationdate) <= notificationDays) {
                    List<ActiveScratchOrg> tmp = (notifiableOrgs.containsKey(org.OwnerId)) ? notifiableOrgs.get(org.OwnerId) : new List<ActiveScratchOrg>();
                    tmp.add(org);
                    notifiableOrgs.put(org.OwnerId, tmp);
                }
            }
        } else {
            System.debug(LoggingLevel.ERROR, 'You don\'t have access to ActiveScratchOrgs.');
        }

        return notifiableOrgs;
    }

    public static Boolean emailOrgOwners(Map<Id, List<ActiveScratchOrg>> notifiableOrgs) {
        if (ScratchOrgAlert.ensureEmailObjectPermissions()
            && ScratchOrgAlert.isObjectAccessible(Schema.SObjectType.User, ScratchOrgAlert.UserQueryFields)
            && ScratchOrgAlert.isObjectAccessible(Schema.SObjectType.ActiveScratchOrg, ScratchOrgAlert.ActiveScratchOrgQueryFields)
        ) {
            Set<Id> userIds = notifiableOrgs.keySet();
            List<User> users = Database.query('SELECT ' + String.join(ScratchOrgAlert.UserQueryFields, ', ') + ' FROM User WHERE Id IN :userIds');

            List<ScratchOrgAlertEmail__c> emails = new List<ScratchOrgAlertEmail__c>();
            Map<Id, String> recipients = new Map<Id, String>();

            for (User u : users) {
                if (String.isBlank(u.ScratchOrgAlertRecipient__c)) {
                    System.debug('Recipient email not set. Skipping user.');
                    continue;
                } else {
                    recipients.put(u.Id, u.ScratchOrgAlertRecipient__c);
                    emails.add(new ScratchOrgAlertEmail__c(UserId__c = u.Id));
                }
            }
            insert emails;

            List<ScratchOrgAlertEmailItem__c> emailItemList = new List<ScratchOrgAlertEmailItem__c>();
            for (ScratchOrgAlertEmail__c email : emails) {
                for(ActiveScratchOrg o : notifiableOrgs.get(email.UserId__c)) {
                    ScratchOrgAlertEmailItem__c emailItem = new ScratchOrgAlertEmailItem__c();

                    emailItem.CreatedById__c = o.CreatedById;
                    emailItem.CreatedDate__c = o.CreatedDate;
                    emailItem.Description__c = o.Description;
                    emailItem.ScratchOrgAlertEmail__c = email.Id;
                    emailItem.Edition__c = o.Edition;
                    emailItem.ExpirationDate__c = o.ExpirationDate;
                    emailItem.LastLoginDate__c = o.LastLoginDate;
                    emailItem.LastModifiedById__c = o.LastModifiedById;
                    emailItem.LastModifiedDate__c = o.LastModifiedDate;
                    emailItem.LastViewedDate__c = o.LastViewedDate;
                    emailItem.Name__c = o.Name;
                    emailItem.Namespace__c = o.Namespace;
                    emailItem.OrgName__c = o.OrgName;
                    emailItem.OwnerId__c = o.OwnerId;
                    emailItem.ScratchOrg__c = o.ScratchOrg;
                    emailItem.ScratchOrgInfoId__c = o.ScratchOrgInfoId;
                    emailItem.SignupEmail__c = o.SignupEmail;
                    emailItem.SignupInstance__c = o.SignupInstance;
                    emailItem.SignupTrialDays__c = o.SignupTrialDays;
                    emailItem.SystemModstamp__c = o.SystemModstamp;
                    emailItem.SignupUsername__c = o.SignupUsername;

                    emailItemList.add(emailItem);
                }
            }
            insert emailItemList;

            return ScratchOrgAlertEmailer.sendEmails(recipients, [SELECT Id, UserId__c FROM ScratchOrgAlertEmail__c]);
        } else {
            System.debug(LoggingLevel.ERROR, 'You don\'t have access to either the email objects, custom user fields, or ActiveScratchOrgs.');
            return false;
        }
    }

    // Standard business days of Monday-Friday
    public static Integer businessDaysBetween(Date d1, Date d2) {
        Integer days = 0;
        Integer[] dayVal = new Integer[] {0,0,1,1,1,1,1};
        Date aSaturday = Date.newInstance(2017, 5, 27);

        for (Date d = d1; d < d2; d+=1) days += dayVal[math.mod(aSaturday.daysBetween(d),7)];
        return days;
    }

    public static Boolean isObjectAccessible(Schema.DescribeSObjectResult describeResult, String[] fields) {
        Map<String,Schema.SObjectField> perms = describeResult.fields.getMap();
        for (String k : fields) {
            if (!perms.get(k).getDescribe().isAccessible()) {
                return false;
            }
        }
        return true;
    }

    public static Boolean ensureEmailObjectPermissions() {
        Map<String,Schema.SObjectField> emailPermissions = Schema.SObjectType.ScratchOrgAlertEmail__c.fields.getMap();
        for (String k : ScratchOrgAlert.EmailQueryFields) {
            if (!(emailPermissions.get(k).getDescribe().isAccessible() && emailPermissions.get(k).getDescribe().isCreateable())) {
                return false;
            }
        }

        Map<String,Schema.SObjectField> emailItemPermissions = Schema.SObjectType.ScratchOrgAlertEmailItem__c.fields.getMap();
        for (String k : ScratchOrgAlert.EmailItemQueryFields) {
            if (!(emailItemPermissions.get(k).getDescribe().isAccessible() && emailItemPermissions.get(k).getDescribe().isCreateable())) {
                return false;
            }
        }

        return true;
    }

    public static Boolean isObjectUpdateable(Schema.DescribeSObjectResult describeResult, String[] fields) {
        Map<String,Schema.SObjectField> perms = describeResult.fields.getMap();
        for (String k : fields) {
            if (!k.equals('Id') && !perms.get(k).getDescribe().isUpdateable()) {
                return false;
            }
        }

        return true;
    }
}