force-app/main/default/objects/User/fields/ScratchOrgAlertNotificationDays__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertNotificationDays__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of days before a Scratch Org&#39;s expiration that a user should be alerted for.</description>
    <label>Scratch Org Alert Notification Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/ScratchOrgAlertRecipient__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertRecipient__c</fullName>
    <description>The email address that is notified by the Scratch Org Alert app.</description>
    <label>Scratch Org Alert Recipient</label>
    <type>Email</type>
</CustomField>

force-app/tests/default/classes/ScratchOrgAlertTestFactory.cls
public with sharing class ScratchOrgAlertTestFactory {
    
    public static User configureUser(String email, Integer days_before, String additional_emails) {
        User CurrentUser = [select Id, ScratchOrgAlertRecipient__c, ScratchOrgAlertNotificationDays__c
                           from User where Id=:UserInfo.getUserId()];
        CurrentUser.ScratchOrgAlertRecipient__c = email;
        CurrentUser.ScratchOrgAlertNotificationDays__c = days_before;
        update CurrentUser;
        return CurrentUser;
    }

    public static User configureUser(String email, Integer days_before) {
        return configureUser(email, days_before, null);
    }

    public static List<ActiveScratchOrg> populateOrgs() {
        List<ActiveScratchOrg> orgs = new List<ActiveScratchOrg>();

        for(Integer i = 0; i < 5; i++) {
            orgs.add(new ActiveScratchOrg(OwnerId=UserInfo.getUserId()));
        }
        upsert(orgs);
        return orgs;
    }
}