force-app/main/default/objects/User/fields/ScratchOrgAlertNotificationDays__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertNotificationDays__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of days before a Scratch Org&#39;s expiration that a user should be alerted for.</description>
    <label>Scratch Org Alert Notification Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/ScratchOrgAlertRecipient__c.field-meta.xml
<CustomField>
    <fullName>ScratchOrgAlertRecipient__c</fullName>
    <description>The email address that is notified by the Scratch Org Alert app.</description>
    <label>Scratch Org Alert Recipient</label>
    <type>Email</type>
</CustomField>

force-app/tests/default/classes/ScratchOrgAlertSettingsControllerTest.cls
@isTest
public with sharing class ScratchOrgAlertSettingsControllerTest {
    
    @isTest
    public static void TestDefinedUser() {
        ScratchOrgAlertTestFactory.configureUser('test@test.com', 3);
        ScratchOrgAlertSettingsController nsc = new ScratchOrgAlertSettingsController();
        System.assertEquals('test@test.com', nsc.user.ScratchOrgAlertRecipient__c);
        System.assertEquals(3, nsc.user.ScratchOrgAlertNotificationDays__c);
    }

    @isTest
    public static void TestNullUser() {
        ScratchOrgAlertTestFactory.configureUser(null, null);
        ScratchOrgAlertSettingsController nsc = new ScratchOrgAlertSettingsController();
        System.assertEquals(UserInfo.getUserEmail(), nsc.user.ScratchOrgAlertRecipient__c);
        System.assertEquals(ScratchOrgAlertSettingsController.DEFAULT_DAYS_BEFORE, nsc.user.ScratchOrgAlertNotificationDays__c);
    }

    @isTest
    public static void TestSave() {
        ScratchOrgAlertTestFactory.configureUser(null, 3);
        ScratchOrgAlertSettingsController nsc = new ScratchOrgAlertSettingsController();
        nsc.user.ScratchOrgAlertRecipient__c = 'test@test.com';
        nsc.user.ScratchOrgAlertNotificationDays__c = 4;
        nsc.save();
        User CurrentUser = [select Id, ScratchOrgAlertRecipient__c, ScratchOrgAlertNotificationDays__c
                           from User where Id=:UserInfo.getUserId()];
        System.assertEquals('test@test.com', CurrentUser.ScratchOrgAlertRecipient__c);
        System.assertEquals(4, CurrentUser.ScratchOrgAlertNotificationDays__c);
    }

    @isTest
    public static void TestInvalidDaysBefore() {
        ScratchOrgAlertTestFactory.configureUser(null, 3, null);
        ScratchOrgAlertSettingsController nsc = new ScratchOrgAlertSettingsController();
        nsc.user.ScratchOrgAlertNotificationDays__c = -2;
        nsc.save();

        User CurrentUser = [select Id, ScratchOrgAlertNotificationDays__c
                           from User where Id=:UserInfo.getUserId()];
        System.assertEquals(3, CurrentUser.ScratchOrgAlertNotificationDays__c);
    }
}